# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58672d4170972fefc368f2df6097052c6cd0f56fd6a63d752cfd32be7c6814ee8004840ca94eb08f7ac9d20b1011a8013849cba67d65a874264c191db100b2c4

test:
  secret_key_base: 3a993d74c6e6a276d74cb097cebae9fa64ffdd9ab0cba981aa9409a1148071e379cde3503d4f100bb313259107da800596122b5085ee817364806f7dfc12da3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
